# Generated by Django 3.2.7 on 2021-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位列表'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_reponsibility',
        ),
        migrations.AddField(
            model_name='job',
            name='job_responsibility',
            field=models.TextField(default=1, max_length=1024, verbose_name='职位职责'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
